// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVhDwkFBty0TjXKsqCdx7Vuywk1SH_fdc',
    appId: '1:946519379253:web:1566cee503eaa4a3fcd07c',
    messagingSenderId: '946519379253',
    projectId: 'eftkdny',
    authDomain: 'eftkdny.firebaseapp.com',
    storageBucket: 'eftkdny.appspot.com',
    measurementId: 'G-BCCQW2D274',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzwd6pYcHGLq8eEIPrJak541H66WLnTA',
    appId: '1:946519379253:android:dcc7227ddc4ac3fefcd07c',
    messagingSenderId: '946519379253',
    projectId: 'eftkdny',
    storageBucket: 'eftkdny.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjC2Cu2oov-jDp3jq8q27BjV0lbebRL48',
    appId: '1:946519379253:ios:8c2261731a3ba863fcd07c',
    messagingSenderId: '946519379253',
    projectId: 'eftkdny',
    storageBucket: 'eftkdny.appspot.com',
    iosBundleId: 'com.example.eftkdny',
  );
}
